### ISSUE TITLE
Password cracking lab sanity check on Windows 10 with community-enhanced John 1.8.0-jumbo-1 errors with "Couldn't compute FAST_CWD pointer"

### ISSUE THREAD

**Issue by aubrel** [AnarchoTechNYC/meta#15]
On Windows 10, after placing `sanitycheck.password.txt` and `sanitycheck.wordlist.txt` into `run` in `john`, and attempting to execute `.\john --wordlist=sanitycheck.wordlist.txt sanitycheck.wordlist.txt`, I received the following error:

`2 [main] john 352 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer. 
Please report this problem to the public mailing list cygwin@cygwin.com
No password hashes loaded (see FAQ)`

**Comment by meitar** [comment]
No updates in more than three years, closing as abandoned. (Who's using `john` on Windows anymore, anyways?)
