### ISSUE TITLE
Mr Robot's Netflix & Hack 3/21

### ISSUE THREAD

**Issue by oscarthecouch** [AnarchoTechNYC/meta#16]
Hey all, there will be a Mr Robot's Netflix n' Hack meeting to watch episode 4 at 268 Kosciuszko st at 7pm this Tuesday, 3/21. Hope to see you!

**Comment by Hypolite** [comment]
Sorry, can't make it ☹️

**Comment by meitar** [comment]
Hope it went well! :)
