### ISSUE TITLE
Mr. Robot's Netflix 'n' Hack 5/6

### ISSUE THREAD

**Issue by oscarthecouch** [AnarchoTechNYC/meta#18]
Hey all, we'll be watching episode 7 of Mr Robot for a [Mr. Robot's Netflix 'n' Hack](https://github.com/AnarchoTechNYC/meta/wiki/Mr.-Robot's-Netflix-'n'-Hack) event at Koz House (DM for address) at 8pm Saturday 5/6. Hope to see you!

**Comment by meitar** [comment]
@oscarthecouch Just an FYI, the list of tools, techniques, and procedures ("[TTPs](http://forensicswiki.org/wiki/Cyber_Threat_Intelligence#TTP)") is currently empty for [Episode 8](https://github.com/AnarchoTechNYC/meta/wiki/Mr.-Robot's-Netflix-'n'-Hack#week-8-s01e08), I never got around to taking notes that far through the show. This is fine, it just means that you may not have a detailed accounting of the tech shown on the show, and/or may need to write the first draft of the list yourself if you can and would like to do that.

Also, I know that @zachmandeville, @aubrel, and I were talking about taking some time to start filling in the Episode 8 TTPs as well, but I don't think we'll get around to it by Saturday.

**Comment by oscarthecouch** [comment]
Well we'll have a couple weeks to work on it while we do ep7 this time. Thx for the heads up!

**Comment by meitar** [comment]
Oh! Perfect! :)

**Comment by meitar** [comment]
And thus a good time was had by all, the end. :)
