### ISSUE TITLE
Damn Vulnerable iOS App (link update request)

### ISSUE THREAD

**Issue by metamonsta** [AnarchoTechNYC/meta#19]
Seems the link to download the DVIA framework is down. OWASP and the author seem to be pointing seekers to the authors official site and githib project page (see below)

Author page (includes the currently "down" DVIA download link, but also has DVIA tutorials and other supplemental documents and guides): https://n0where.net/damn-vulnerable-ios-app-dvia/

Authors DVIA github project page: https://github.com/prateek147/DVIA

OWASP's link and writeup of the DVIA project: https://www.owasp.org/index.php/OWASP_DVIA#tab=Framework

:)

**Comment by meitar** [comment]
Most of the links still point to `damnvulnerableiosapp.com`. That domain was [online as of a couple weeks ago](https://web.archive.org/web/20170606042815/http://damnvulnerableiosapp.com/), so I say we give it a little while longer, wait and see if it returns. Meanwhile, an Internet search on "Damn Vulnerable iOS App" still returns meaningful results for those who are impatient or especially curious.

**Comment by meitar** [comment]
The [damnvulnerableiosapp.com domain has returned](https://web.archive.org/web/20170712081553/http://damnvulnerableiosapp.com/), so no updates to the wiki are required.

**Comment by metamonsta** [comment]
Indeed it is. thanks all :)
