### ISSUE TITLE
OnionShare materials have outdated screenshots

### ISSUE THREAD

**Issue by meitar** [AnarchoTechNYC/meta#20]
The screenshots in our OnionShare materials ("[Secretly sharing files with OnionShare and Tor Browser](https://github.com/AnarchoTechNYC/meta/tree/master/train-the-trainers/mr-robots-netflix-n-hack/week-1/secretly-sharing-files-with-onionshare-and-tor-browser)") show OnionShare version 1.2, but OnionShare version 1.3 has dramatically changed the GUI.

It would be nice if the workshop materials were updated to reflect the new interface. :)

**Comment by notmike** [comment]
I submitted a pull request =)
