### ISSUE TITLE
Split Mr. Robot's Netflix 'n' Hack into separate pages.

### ISSUE THREAD

**Issue by aubrel** [AnarchoTechNYC/meta#23]
The [Mr. Robot's Netflix 'n' Hack wiki](https://github.com/AnarchoTechNYC/meta/wiki/Mr.-Robot's-Netflix-'n'-Hack#week-5-s01e05) is hard to navigate with how long it is and how many images are now involved in it; it may be more easily navigated if the sections were their own pages.

**Comment by meitar** [comment]
On the other hand, if they are their own pages, it will more bore difficult to use `CTRL-F` to find a given topic. I'm conflicted about whether or not this should be done, but discussion is welcome.

**Comment by aubrel** [comment]
I think they should be separated - using them as one page is really tough; maybe there is a way to split them into pages, but have a landing page of some sort that describes what each "Week" involves, so that finding the material one is looking for is easier? I often use the Mr. Robot guides because I want to find an example/info on some specific tool. For example, let's say I wanted to know about malware on USB sticks. Okay, that's Week 6. If each week had its own page, there could be some kind of brief list or description like:

# Week 6

## Topics

* USB malware
* Printer security
    * Printer dots
*  Industrial Control Systems

etc....?

**Comment by meitar** [comment]
No action, probably unnecessary.
