### ISSUE TITLE
Fix page on GPG/PGP.

### ISSUE THREAD

**Issue by aubrel** [AnarchoTechNYC/meta#26]
The [page on GPG/PGP](https://github.com/AnarchoTechNYC/meta/wiki/GPG-and-PGP) is now existent, but is missing a _ton_ of info; this could be better, without being overwhelming or redundant.

**Comment by meitar** [comment]
I think that page is best utilized as a portal, not a guide in and of itself. No need to do the work of explaining what GPG is, as many people have done that already. :) See [my recent edits](https://github.com/AnarchoTechNYC/meta/wiki/GPG-and-PGP/_compare/79febc7f4dfa0acd4548e0f770af50e0ff620a65...58a1111e55a0306ccaf3de1a8615d1dc11cc2a21). No one is assigned to this issue so I'm closing. Feel free to re-open if you want to discuss further.
