### ISSUE TITLE
Make new desktops for `blue_desktop` and `red`.

### ISSUE THREAD

**Issue by aubrel** [AnarchoTechNYC/meta#29]
See: [Arp cache poisoning](https://github.com/AnarchoTechNYC/meta/tree/master/train-the-trainers/black-hat-bash-back/arp-cache-poisoning)

The ones we have now are fine, but could be spiffier!

**Comment by meitar** [comment]
These are okay for the time being and there are bigger fish to fry. :) If anyone would like to pick this up in the future, please feel free to have fun with it.
