### ISSUE TITLE
What guides are we actually responsible for compiling on our wiki?

### ISSUE THREAD

**Issue by meitar** [AnarchoTechNYC/meta#3]
Our new wiki has been created with a simple structure imported from several other orgs for whom I've created some organizational memory. One of the open questions for the AnarchoTechNYC wiki itself is what should go under our "Training guides" section.

For now, we are focusing on the tech side of things; those redlinks on the wiki homepage need to be either filled in or, if they're left as redlinks for a while, that part of the wiki just needs to be pared down.

I'm not certain we have an answer for this immediately so I'm opening this issue as a place for me to keep track of any discussion I have about it in the near future.

**Comment by nthrow** [comment]
I think pentesting and opsec resources would be the obvious candidates, perhaps eventually discriminating the 'introductory' guides geared towards activists and normies alike from the more in-depth training courses should the two become cluttered in due time.

**Comment by meitar** [comment]
@nthrow I think you're right.

Over the past couple of months I've been investing energy into creating "beginner-friendly" infosec resources, but have not yet created a "Reader's Digest" of these resources as a "Guide."

Currently we have [a "Guides and Advice" section on our wiki homepage](https://github.com/AnarchoTechNYC/meta/wiki#guides-and-advice), and it links to several guides, but only one really exists: Security culture guide.

However, I don't think we're really creating a *security culture* guide, as many of those already exist. What we actually want is a guide that *links to* a subset of those guides, and possibly some others. This *sort of* already exists [in the "For defenders" section of the InfoSec wiki page](https://github.com/AnarchoTechNYC/meta/wiki/InfoSec#for-defenders), but that list is hyper-specific with respect to digital security.

So, moving forward, maybe we should do one (or more) of the following:

* Create a similar list in the Security culture guide as the InfoSec § For Defenders stuff, that is more general?
* Redeclare our purpose with the "Security culture guide" as more specifically focused on digital stuff? (It doesn't look like anyone else is really using this organizing space, anyway.)
* Position the InfoSec page's material as a more clearly-signposted subset of the Security culture guide.

**Comment by meitar** [comment]
I've made an executive decision and revamped the guides section to focus solely on "welcoming" material. I consider this issue closed. Feel free to re-open if there are objections.

**Comment by meitar** [comment]
Ping @nthrow, I've revisited this and decided to massively restructure the "guides" section in a more narrow way to reflect the sort of information that we actually developed. Have a peek at the new [Security culture](https://github.com/AnarchoTechNYC/meta/wiki/Security-culture) portal page if you're interested.
