### ISSUE TITLE
Guide in different languages

### ISSUE THREAD

**Issue by benmezger** [AnarchoTechNYC/meta#32]
How can we separate translations? I started writing the same, with some changes [here](http://guide.seds.nl), I wonder how can we link it with this guide.

**Comment by meitar** [comment]
I would love to see translations of all Anarcho-Tech NYC content! :) If you would like to publish these translations in the Anarcho-Tech NYC repository, I would use an [ISO 639](http://www.iso.org/iso/home/standards/language_codes.htm) language code as a suffix for the file. For instance, `README.pt.md` for Portuguese or `README.es.md` for Spanish. If you are wanting to translate wiki pages, I would suggest the same, except that these suffixes would be part of the title of the page. For example, `Home.es.md` for the Spanish homepage.

This is a simplest-thing-that-could-possibly-work situation and obviously not the most elegant solution. But, for now, that's all we can easily support and also all I think we need.

**Comment by benmezger** [comment]
Hm, but then keep them in the same directory? Would't a something like a directory with English, Portuguese, etc be a better approach?

**Comment by meitar** [comment]
> Would't a something like a directory with English, Portuguese, etc be a better approach?

Perhaps, but that would be incompatible with Gollum's filesystem structure. We can always restructure easily enough with something like

```sh
mkdir pt
mv *.pt.md pt
```

so it wouldn't be hard to switch if it becomes more feasible in the future. `¯\_(ツ)_/¯`

**Comment by meitar** [comment]
No updates in almost a year, so I'm closing this issue as abandoned.
