### ISSUE TITLE
Onionshare does v3 links too

### ISSUE THREAD

**Issue by KwadroNaut** [AnarchoTechNYC/meta#37]
https://github.com/AnarchoTechNYC/meta/wiki/Connecting-to-an-authenticated-Onion-service  "ad. OnionShare's "Advanced" options will automate the server-side portion of creating an authenticated stealth Version 2 Onion service."

This February a new OnionShare was released with v3 URLs, authenticated onions are only available with v2 through OnionShare, otherwise possible, but manual procedure.

**Comment by meitar** [comment]
> This February a new OnionShare was released with v3 URLs, authenticated onions are only available with v2 through OnionShare, otherwise possible, but manual procedure.

We know, but there's no edit to be made (or even suggested?) here, so I'm closing this issue as a no-op.
