### ISSUE TITLE
"Basics of Making a Rootkit" broken link

### ISSUE THREAD

**Issue by amerkay** [AnarchoTechNYC/meta#38]
Quick note, the link to "Basics of Making a Rootkit" on the [main page of the wiki](https://github.com/AnarchoTechNYC/meta/wiki/Mr.-Robot's-Netflix-'n'-Hack#week-1-s01e01) is broken. [Archived page available here](https://web.archive.org/web/20170205155013/https://d0hnuts.com/2016/12/21/basics-of-making-a-rootkit-from-syscall-to-hook/).

**Comment by meitar** [comment]
Thanks, fixed.
