### ISSUE TITLE
Confirm a time+space for "Mr. Robot's Netflix 'n' Hack" nights

### ISSUE THREAD

**Issue by meitar** [AnarchoTechNYC/meta#4]
One of our "[train the trainers in cybersecurity](https://github.com/AnarchoTechNYC/projects/1)" events is going to be a "[Mr. Robot's Netflix 'n' Hack](https://github.com/AnarchoTechNYC/meta/wiki/Mr.-Robot's-Netflix-'n'-Hack)" night; a relatively gentle introduction to the tools, techniques, and procedures (TTPs) used in the real world of digital security.

We need a physical space that meets the following criteria:

* [ ] big enough for at least 10 people and their laptops to comfortably fit
* [ ] has a projector or large screen TV on which to view episodes of the show and demo TTPs
* [ ] has adjustable lighting so we can actually visibly see the projected screen
* [ ] has reliable Wi-Fi internet connectivity for all participants
* [ ] is available at the same time each week (or multiple venues that all match the above criteria that we can hop around to/from)

See also: [How to facilitate Mr. Robot's Netflix 'n' Hack](https://github.com/AnarchoTechNYC/meta/wiki/How-to-facilitate-Mr.-Robot's-Netflix-'n'-Hack)

**Comment by oscarthecouch** [comment]
Hey I have a space! It's in bed stuy. Working on determining a time we may be able to use it, may not be until after new years at this point unfortunately. Who's into it?

**Comment by meitar** [comment]
This is mostly happening at @oscarthecouch's discretion, so I'm calling this more or less "confirmed." Individual events can have their own issue threads for clarity. :)
