### ISSUE TITLE
Orbot Client Authorization Wiki Updates 

### ISSUE THREAD

**Issue by bitmold** [AnarchoTechNYC/meta#41]
This commit contains updated instructions for the wiki page on connecting to authenticated onion services. The changes all pertain to Orbot 16.5 which is unreleased but has v3 support. 

Changes Include:

- newly added v3 client auth instructions  
- updated v2 instructions 
    - removed orfox stuff
    - updated menu instructions to reflect how the v2 stuff is now buried behind another menu within Orbot 

https://github.com/bitmold/onionservicewikifork/commit/b278b37c3bb769b52639b01dd85e52541bea41d3

please feel free to do with this as y'all wish

**Comment by fabacab** [comment]
Thank you for this. Your patch was applied as commit 6e5adbc08a46e6b24b0a86cfd1511b1c07881001.
