### ISSUE TITLE
Create "persona-focused" anti-surveillance and security resource guide

### ISSUE THREAD

**Issue by meitar** [AnarchoTechNYC/meta#6]
There are already a lot of tool-specific guides for digital (and other) security. Yay! Let's not re-create those. However, people are still asking us questions like:

* "As the administrator of my group's website, what do I need to know to store my group's data more securely?"
* "As an individual advocating for LGBT rights, what do I need to do to protect myself from SWAT'ing?"

and so on. Not all tools are relevant in all circumstances. Can we create some *brief* guides that leverage the existing detailed guides for more specific threat models? Can we help people more intuitively perform a threat assessment for themselves without reinventing the wheels others have already built?

I think the answer is yes, and propose a "persona-focused" guide on our wiki as a place to start.

**Comment by benmezger** [comment]
By guide do you mean a step by step of configuring tool x? Or a guide explaining tool x and recommended for a particular threat model?

**Comment by meitar** [comment]
> By guide do you mean a step by step of configuring tool x? Or a guide explaining tool x and recommended for a particular threat model?
This issue is was created before [this page](https://github.com/AnarchoTechNYC/meta/wiki/Persona-based-commsec-training-matrix), but that's what it's refering to.

**Comment by meitar** [comment]
I'm gonna mark this complete, actually, even though the individual page itself is not "done," and probably won't ever be. But it's useful enough for now for us to continue to keep adding to it.
