### ISSUE TITLE
Should we have a "persona-focused" list of tools/services? 

### ISSUE THREAD

**Issue by benmezger** [AnarchoTechNYC/meta#7]
Wouldn't it be nice to have a full list of tools/services one could use? A list of "trusted" email providers, social networking alternatives and so on?

**Comment by meitar** [comment]
You mean like the [Persona-based commsec training matrix](https://github.com/AnarchoTechNYC/meta/wiki/Persona-based-commsec-training-matrix)? Categorized lists of tools already exist in the form of, for instance, [PRISM-Break.org](https://prism-break.org/), also linked from our own "matrix."

**Comment by meitar** [comment]
This seems redundant now considering #6.
